### ISSUE TITLE
Possible Injection with Shell=True 

### ISSUE THREAD

**Issue by lfatty** [cfpb/sentia#14]
I was looking at the source code and noted that you have lot of Shell=TRUE. See the following lines:

/sentia/softwarediscovery/get_installed_software.py on line 94
/sentia/softwarediscovery/get_installed_software.py on line 108
/sentia/softwarediscovery/get_installed_software.py on line 124
/sentia/softwarediscovery/get_installed_software.py:142
sentia/softwarediscovery/get_installed_software.py:165

If someone (malicious person) executes shell commands that might include unsanitized input from an untrusted source, it will make the application vulnerable to shell injection, a serious security flaw which can result in arbitrary command execution. For this reason, the use of shell=True is strongly discouraged in cases where the command string is constructed from external input.

**Comment by DarthDippy** [comment]
Thanks for the catch on this!

**Comment by djdrisco** [comment]
Move scripts to separate project: github.com/cfpb/sentia-softwarediscovery
